config/routes.rb
Rails.application.routes.draw do
  root 'cms#index' # This will be website entry point
  get 'cms/index' # Please open CmsController and load method index
  resources :weapons
  resources :spells
  resources :characters
  resources :character_types

end

app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :character_type, :class_name => 'CharacterType'

	# Type of character is require 
	validates_presence_of :character_type_id

	# Name is require
	validates_presence_of :name

	# Name should be less than 100 characters
	validates_length_of :name, maximum: 100
end

app/models/character_type.rb
class CharacterType < ActiveRecord::Base
	has_many :characters
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  before_action :prepare_form_data, only: [:new, :edit]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character
      .joins(:character_type)
      .select('characters.id, 
               characters.name, 
               characters.is_good_character,
               character_types.name as type'
      )
      .all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:character_type_id, :name, :is_good_character)
    end

    # Get necessary information for _form view
    def prepare_form_data
      @character_types = CharacterType.all

      puts YAML::dump @character_types
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%# debug(@character_types) %>

<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :characters_type_id %></br>

    <%= collection_select(:character, :character_type_id, @character_types, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_good_character %><br>
    <%= f.check_box :is_good_character %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characters</h1>

<table>
  <thead>
    <tr>
      <th>Characters type</th>
      <th>Name</th>
      <th>Is good character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.type %></td>
        <td><%= character.name %></td>
        <td>
          <%= character.is_good_character %>
        </td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Characters type:</strong>
  <% unless (@character.character_type.nil?) %>
  	<%= @character.character_type.name %>
  <% end %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Is good character:</strong>
  <%= @character.is_good_character %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>