config/routes.rb
Rails.application.routes.draw do
  root 'cms#index' # This will be website entry point
  get 'cms/index' # Please open CmsController and load method index
  resources :weapons
  resources :spells
  resources :characters
  resources :character_types

end

app/models/spell.rb
class Spell < ActiveRecord::Base
	# Name is require
	validates_presence_of :name

	# Name should be less than 100 characters
	validates_length_of :name, maximum: 100

	# Mana property is require
	validates_presence_of :mana

	# Mana property should be between 1 and 100
	validates :mana, :numericality => { :greater_than => 0, :less_than_or_equal_to => 100 }
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]

  # GET /spells
  # GET /spells.json
  def index
    @spells = Spell.all
  end

  # GET /spells/1
  # GET /spells/1.json
  def show
  end

  # GET /spells/new
  def new
    @spell = Spell.new
  end

  # GET /spells/1/edit
  def edit
  end

  # POST /spells
  # POST /spells.json
  def create
    @spell = Spell.new(spell_params)

    respond_to do |format|
      if @spell.save
        format.html { redirect_to @spell, notice: 'Spell was successfully created.' }
        format.json { render :show, status: :created, location: @spell }
      else
        format.html { render :new }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spells/1
  # PATCH/PUT /spells/1.json
  def update
    respond_to do |format|
      if @spell.update(spell_params)
        format.html { redirect_to @spell, notice: 'Spell was successfully updated.' }
        format.json { render :show, status: :ok, location: @spell }
      else
        format.html { render :edit }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spells/1
  # DELETE /spells/1.json
  def destroy
    @spell.destroy
    respond_to do |format|
      format.html { redirect_to spells_url, notice: 'Spell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spell_params
      params.require(:spell).permit(:name, :mana)
    end
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/spells/_form.html.erb
<%= form_for(@spell) do |f| %>
  <% if @spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
      <% @spell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mana %><br>
    <%= f.number_field :mana %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spells/edit.html.erb
<h1>Editing Spell</h1>

<%= render 'form' %>

<%= link_to 'Show', @spell %> |
<%= link_to 'Back', spells_path %>

app/views/spells/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Spells</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mana</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= spell.name %></td>
        <td><%= spell.mana %></td>
        <td><%= link_to 'Show', spell %></td>
        <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
        <td><%= link_to 'Destroy', spell, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spell', new_spell_path %>

app/views/spells/new.html.erb
<h1>New Spell</h1>

<%= render 'form' %>

<%= link_to 'Back', spells_path %>

app/views/spells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spell.name %>
</p>

<p>
  <strong>Mana:</strong>
  <%= @spell.mana %>
</p>

<%= link_to 'Edit', edit_spell_path(@spell) %> |
<%= link_to 'Back', spells_path %>