config/routes.rb
Rails.application.routes.draw do
  root 'cms#index' # This will be website entry point
  get 'cms/index' # Please open CmsController and load method index
  resources :weapons
  resources :spells
  resources :characters
  resources :character_types

end

app/controllers/character_types_controller.rb
class CharacterTypesController < ApplicationController
  before_action :set_character_type, only: [:show, :edit, :update, :destroy]

  # GET /character_types
  # GET /character_types.json
  def index
    @character_types = CharacterType.all
  end

  # GET /character_types/1
  # GET /character_types/1.json
  def show
  end

  # GET /character_types/new
  def new
    @character_type = CharacterType.new
  end

  # GET /character_types/1/edit
  def edit
  end

  # POST /character_types
  # POST /character_types.json
  def create
    @character_type = CharacterType.new(character_type_params)

    respond_to do |format|
      if @character_type.save
        format.html { redirect_to @character_type, notice: 'Character type was successfully created.' }
        format.json { render :show, status: :created, location: @character_type }
      else
        format.html { render :new }
        format.json { render json: @character_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_types/1
  # PATCH/PUT /character_types/1.json
  def update
    respond_to do |format|
      if @character_type.update(character_type_params)
        format.html { redirect_to @character_type, notice: 'Character type was successfully updated.' }
        format.json { render :show, status: :ok, location: @character_type }
      else
        format.html { render :edit }
        format.json { render json: @character_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_types/1
  # DELETE /character_types/1.json
  def destroy
    @character_type.destroy
    respond_to do |format|
      format.html { redirect_to character_types_url, notice: 'Character type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character_type
      @character_type = CharacterType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_type_params
      params.require(:character_type).permit(:name)
    end
end

app/helpers/character_types_helper.rb
module CharacterTypesHelper
end

app/views/character_types/_form.html.erb
<%= form_for(@character_type) do |f| %>
  <% if @character_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character_type.errors.count, "error") %> prohibited this character_type from being saved:</h2>

      <ul>
      <% @character_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/character_types/edit.html.erb
<h1>Editing Character Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @character_type %> |
<%= link_to 'Back', character_types_path %>

app/views/character_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Character Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_types.each do |character_type| %>
      <tr>
        <td><%= character_type.name %></td>
        <td><%= link_to 'Show', character_type %></td>
        <td><%= link_to 'Edit', edit_character_type_path(character_type) %></td>
        <td><%= link_to 'Destroy', character_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character type', new_character_type_path %>

app/views/character_types/new.html.erb
<h1>New Character Type</h1>

<%= render 'form' %>

<%= link_to 'Back', character_types_path %>

app/views/character_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character_type.name %>
</p>

<%= link_to 'Edit', edit_character_type_path(@character_type) %> |
<%= link_to 'Back', character_types_path %>